version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "5173:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    restart: unless-stopped
